# Generated by Django 3.2.18 on 2023-03-04 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(default='', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date_requested', models.DateField()),
                ('time_requested', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_requested'],
            },
        ),
    ]
