# Generated by Django 3.2.18 on 2023-03-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_auto_20230304_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_confirmed',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_confirmed',
            field=models.CharField(blank=True, choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], max_length=50),
        ),
    ]
