# Generated by Django 3.2.18 on 2023-03-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_auto_20230304_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_confirmed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_confirmed',
        ),
    ]
